#!/system/bin/sh
# OmniShield — Boot Completed
# Applies resetprop from .profile_props generated by companion_handler.
# On 2nd+ boots, this file persists from the previous session.
# On 1st boot, companion_handler applies resetprop inline when first scoped app launches.

PROPS_FILE="/data/adb/.omni_data/.profile_props"
[ ! -f "$PROPS_FILE" ] && exit 0

RP=/data/adb/ksu/bin/resetprop
[ ! -x "$RP" ] && RP=/data/adb/magisk/resetprop
[ ! -x "$RP" ] && RP=resetprop

while IFS='=' read -r key value; do
    [ -z "$key" ] && continue
    case "$key" in \#*) continue ;; esac
    "$RP" -n "$key" "$value" 2>/dev/null
done < "$PROPS_FILE"

# PR76: Fix Settings.Global device_name — Binder IPC, not interceptable via JNI.
# Read model from persist.sys.device_name already written to .profile_props.
_DN=$(grep "^persist.sys.device_name=" "$PROPS_FILE" 2>/dev/null | cut -d'=' -f2- | tr -d '\r\n')
[ -n "$_DN" ] && settings put global device_name "$_DN" 2>/dev/null
