#!/system/bin/sh
# OmniShield Post-FS-Data
# Must run BEFORE Zygote to set kernel uname via susfs.
mkdir -p /data/adb/.omni_data

SUSFS_BIN=/data/adb/ksu/bin/ksu_susfs
CFG=/data/adb/.omni_data/.identity.cfg

if [ -x "$SUSFS_BIN" ] && [ -f "$CFG" ]; then
    PROFILE=$(grep "^profile=" "$CFG" | cut -d'=' -f2-)
    if [ -n "$PROFILE" ]; then
        case "$PROFILE" in
            # Real device (lancelot/MT6768) — same as other MT6768
            "Redmi 9")
                KV="4.14.186-perf+" ;;
            # Samsung MTK MT6768 — numeric kernel suffix (not -perf+)
            "Galaxy A31"|"Samsung Galaxy A31")
                KV="4.14.113-25267920" ;;
            # Samsung MTK MT6769 — numeric kernel suffix (not -perf+)
            "Galaxy A32 4G"|"Galaxy A22 4G")
                KV="4.14.113-23424440" ;;
            # Samsung Exynos 850 — numeric kernel suffix
            "Galaxy A21s")
                KV="4.19.113-25351273" ;;
            # All other MediaTek profiles (MT6768/MT6769/MT6785/MT6833/MT6853)
            "Redmi 10X 4G"|"POCO M3 Pro 5G"|"Galaxy A32 5G"|"Realme 8"|\
            "Redmi 9 Prime"|"Redmi Note 9"|"Tecno Spark 6"|"Vivo S1"|\
            "Vivo Y19"|"Vivo Y20G"|"POCO M2"|"Realme Narzo 20"|\
            "Realme Narzo 10"|"Realme 6i"|"Moto G31"|"Realme C25s"|\
            "Infinix Note 10"|"Redmi Note 8 2021"|"Moto G41"|\
            "Realme Narzo 30A"|"Realme Narzo 50A"|"Infinix Hot 10s"|\
            "Infinix Note 11i"|"Tecno Pova 2"|"Tecno Spark 8 Pro"|\
            "Realme 6i Pro"|"Tecno Camon 17")
                KV="4.14.186-perf+" ;;
            *)
                KV="4.14.186-perf+" ;;
        esac
        $SUSFS_BIN set_uname "$KV" '#1 SMP PREEMPT' 2>/dev/null

        # PR79: SUSFS cmdline forgery — kernel-level /proc/cmdline spoof
        # .cmdline is generated by companion_handler() C++ (hybrid format).
        # On 2nd+ boots it persists from previous session.
        if [ -f /data/adb/.omni_data/.cmdline ]; then
            $SUSFS_BIN set_cmdline_or_bootconfig /data/adb/.omni_data/.cmdline 2>/dev/null
        fi
    fi
fi
