#!/system/bin/sh
# OmniShield Post-FS-Data
# Must run BEFORE Zygote to set kernel uname via susfs.
mkdir -p /data/adb/.omni_data

SUSFS_BIN=/data/adb/ksu/bin/ksu_susfs
CFG=/data/adb/.omni_data/.identity.cfg

if [ -x "$SUSFS_BIN" ] && [ -f "$CFG" ]; then
    PROFILE=$(grep "^profile=" "$CFG" | cut -d'=' -f2-)
    if [ -n "$PROFILE" ]; then
        case "$PROFILE" in
            "Redmi 9")
                KV="4.14.186-perf+" ;;
            "Pixel 5"|"Pixel 4a 5G")
                KV="4.19.113-g820a424c538c-ab7336171" ;;
            "Pixel 4a")
                KV="4.14.150-g62a62a5a93f7-ab7336171" ;;
            "Pixel 3a XL")
                KV="4.9.189-g5d098cef6d96-ab6174032" ;;
            "Redmi 10X 4G"|"POCO M3 Pro 5G"|"Galaxy A32 5G"|"Galaxy A12"|\
            "Galaxy A31"|"Realme 8")
                KV="4.14.141-perf+" ;;
            "Mi 10T"|"Mi 11"|"POCO F3"|"Galaxy S20 FE"|"OnePlus 8T"|\
            "OnePlus 8"|"Moto Edge Plus"|"ASUS ZenFone 7")
                KV="4.19.157-perf+" ;;
            "Redmi Note 10 Pro"|"Redmi Note 9 Pro"|"POCO X3 NFC"|"Mi 11 Lite"|\
            "Galaxy A52"|"Galaxy A72"|"OnePlus Nord"|"Moto Edge"|\
            "Nokia 8.3 5G"|"Realme 8 Pro")
                KV="4.19.113-perf+" ;;
            "Moto G Power 2021"|"Moto G Stylus 2021"|"OnePlus N10 5G"|"Nokia 5.4")
                KV="4.19.157-perf+" ;;
            "Realme GT Master")
                KV="5.4.61-perf+" ;;
            "Galaxy A51"|"Galaxy M31")
                KV="4.14.113-25145160" ;;
            "Galaxy F62")
                KV="4.14.113-22911262" ;;
            "Galaxy A21s")
                KV="4.19.113-25351273" ;;
            *)
                KV="4.14.186-perf+" ;;
        esac
        $SUSFS_BIN set_uname "$KV" '#1 SMP PREEMPT' 2>/dev/null

        # PR79: SUSFS cmdline forgery — kernel-level /proc/cmdline spoof
        # .cmdline is generated by companion_handler() C++ (hybrid format).
        # On 2nd+ boots it persists from previous session.
        if [ -f /data/adb/.omni_data/.cmdline ]; then
            $SUSFS_BIN set_cmdline_or_bootconfig /data/adb/.omni_data/.cmdline 2>/dev/null
        fi
    fi
fi
